# Generated by Django 5.2.7 on 2025-10-29 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='origin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.location'),
            preserve_default=False,
        ),
    ]
