# Generated by Django 5.2.7 on 2025-10-31 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_dish_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='photo',
            field=models.URLField(blank=True),
        ),
    ]
