# Generated by Django 5.2.7 on 2025-11-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_tag_dish_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='main_app.tag'),
        ),
    ]
